export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  FINANCE_MANAGER = 'FINANCE_MANAGER',
  STAFF = 'STAFF',
  VIEWER = 'VIEWER',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
}

export enum EntityStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BLOCKED = 'BLOCKED',
}

export enum DealStatus {
  DRAFT = 'DRAFT',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  APPROVED = 'APPROVED',
  ACTIVE = 'ACTIVE',
  COMPLETED = 'COMPLETED',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
  DEFAULTED = 'DEFAULTED',
}

export enum InterestType {
  FLAT = 'FLAT',
  REDUCING_BALANCE = 'REDUCING_BALANCE',
  CUSTOM = 'CUSTOM',
}

export enum RepaymentFrequency {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  BI_WEEKLY = 'BI_WEEKLY',
  MONTHLY = 'MONTHLY',
  CUSTOM = 'CUSTOM',
}

export enum FundingSourceType {
  COMPANY = 'COMPANY',
  PARTNER = 'PARTNER',
  OUTSIDE_INVESTOR = 'OUTSIDE_INVESTOR',
}

export enum FundingStatus {
  COMMITTED = 'COMMITTED',
  DISBURSED = 'DISBURSED',
  SETTLED = 'SETTLED',
}

export enum ScheduleStatus {
  UPCOMING = 'UPCOMING',
  DUE = 'DUE',
  PARTIALLY_PAID = 'PARTIALLY_PAID',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  WAIVED = 'WAIVED',
}

export enum PaymentMethod {
  CASH = 'CASH',
  BANK_TRANSFER = 'BANK_TRANSFER',
  UPI = 'UPI',
  CHEQUE = 'CHEQUE',
  OTHER = 'OTHER',
}

export enum RepaymentStatus {
  PROCESSED = 'PROCESSED',
  REVERSED = 'REVERSED',
  FLAGGED = 'FLAGGED',
}

export enum AccountType {
  ASSET = 'ASSET',
  LIABILITY = 'LIABILITY',
  EQUITY = 'EQUITY',
  REVENUE = 'REVENUE',
  EXPENSE = 'EXPENSE',
}

export enum TransactionType {
  FUNDING_RECEIVED = 'FUNDING_RECEIVED',
  CLIENT_FINANCE_DISBURSED = 'CLIENT_FINANCE_DISBURSED',
  CLIENT_REPAYMENT = 'CLIENT_REPAYMENT',
  INVESTOR_RETURN = 'INVESTOR_RETURN',
  PARTNER_RETURN = 'PARTNER_RETURN',
  COMPANY_COMMISSION = 'COMPANY_COMMISSION',
  EXPENSE = 'EXPENSE',
  ADJUSTMENT = 'ADJUSTMENT',
}

export enum NotificationType {
  REPAYMENT_DUE = 'REPAYMENT_DUE',
  REPAYMENT_OVERDUE = 'REPAYMENT_OVERDUE',
  INVESTOR_PAYMENT_DUE = 'INVESTOR_PAYMENT_DUE',
  DEAL_APPROVAL_REQUIRED = 'DEAL_APPROVAL_REQUIRED',
  DEAL_APPROVED = 'DEAL_APPROVED',
  DEAL_COMPLETED = 'DEAL_COMPLETED',
  PAYMENT_RECEIVED = 'PAYMENT_RECEIVED',
  SYSTEM_ALERT = 'SYSTEM_ALERT',
}
